# Generated by Django 4.0.6 on 2022-08-06 20:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='libro',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('autor', models.CharField(max_length=100)),
                ('categoria', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='pelicula',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('director', models.CharField(max_length=100)),
                ('tematica', models.CharField(max_length=100)),
                ('ano_estreno', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='persona',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('edad', models.IntegerField()),
                ('email', models.EmailField(max_length=254)),
                ('libros_preferidos', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='libreria.libro')),
                ('peliculas_preferidas', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='libreria.pelicula')),
            ],
        ),
    ]
