# Generated by Django 4.0.6 on 2022-08-08 22:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('libreria', '0002_perfil'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Perfil',
        ),
    ]
