# Generated by Django 4.0.6 on 2022-08-23 00:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('libreria', '0004_avatar'),
    ]

    operations = [
        migrations.RenameField(
            model_name='avatar',
            old_name='user',
            new_name='usuario',
        ),
    ]
