# Generated by Django 4.0.6 on 2022-08-23 00:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('libreria', '0005_rename_user_avatar_usuario'),
    ]

    operations = [
        migrations.RenameField(
            model_name='avatar',
            old_name='usuario',
            new_name='user',
        ),
    ]
