# Generated by Django 4.0.6 on 2022-08-27 14:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('libreria', '0006_rename_usuario_avatar_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='libro',
            name='tapa',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
