# Generated by Django 4.0.6 on 2022-09-04 12:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('libreria', '0007_libro_tapa'),
    ]

    operations = [
        migrations.DeleteModel(
            name='persona',
        ),
    ]
